import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    'Fluent-React-Charting',
    'TechnicalDetails',
    'colors',
    'implementing-2-to-1-spacing',
    'TestingStrategy',
    {
      type:'category',
      label:'Test Plans',
      items:[
        {
          type: 'autogenerated',
          dirName:'Test Plans',
        }
      ]
    }
  ],
   
};

export default sidebars;
