// The tokens are designed to match with https://github.com/microsoft/fluentui/blob/master/packages/tokens/src/tokens.ts
export const FluentV9ColorTokens = {
    colorNeutralForeground1: '--colorNeutralForeground1' as const,
    colorNeutralForeground1Hover: '--colorNeutralForeground1Hover' as const,
    colorNeutralForeground1Pressed: '--colorNeutralForeground1Pressed' as const,
    colorNeutralForeground1Selected: '--colorNeutralForeground1Selected' as const,
    colorNeutralForeground2: '--colorNeutralForeground2' as const,
    colorNeutralForeground2Hover: '--colorNeutralForeground2Hover' as const,
    colorNeutralForeground2Pressed: '--colorNeutralForeground2Pressed' as const,
    colorNeutralForeground2Selected: '--colorNeutralForeground2Selected' as const,
    colorNeutralForeground2BrandHover: '--colorNeutralForeground2BrandHover' as const,
    colorNeutralForeground2BrandPressed: '--colorNeutralForeground2BrandPressed' as const,
    colorNeutralForeground2BrandSelected: '--colorNeutralForeground2BrandSelected' as const,
    colorNeutralForeground3: '--colorNeutralForeground3' as const,
    colorNeutralForeground3Hover: '--colorNeutralForeground3Hover' as const,
    colorNeutralForeground3Pressed: '--colorNeutralForeground3Pressed' as const,
    colorNeutralForeground3Selected: '--colorNeutralForeground3Selected' as const,
    colorNeutralForeground3BrandHover: '--colorNeutralForeground3BrandHover' as const,
    colorNeutralForeground3BrandPressed: '--colorNeutralForeground3BrandPressed' as const,
    colorNeutralForeground3BrandSelected: '--colorNeutralForeground3BrandSelected' as const,
    colorNeutralForeground4: '--colorNeutralForeground4' as const,
    colorNeutralForegroundDisabled: '--colorNeutralForegroundDisabled' as const,
    colorBrandForegroundLink: '--colorBrandForegroundLink' as const,
    colorBrandForegroundLinkHover: '--colorBrandForegroundLinkHover' as const,
    colorBrandForegroundLinkPressed: '--colorBrandForegroundLinkPressed' as const,
    colorBrandForegroundLinkSelected: '--colorBrandForegroundLinkSelected' as const,
    colorNeutralForeground2Link: '--colorNeutralForeground2Link' as const,
    colorNeutralForeground2LinkHover: '--colorNeutralForeground2LinkHover' as const,
    colorNeutralForeground2LinkPressed: '--colorNeutralForeground2LinkPressed' as const,
    colorNeutralForeground2LinkSelected: '--colorNeutralForeground2LinkSelected' as const,
    colorCompoundBrandForeground1: '--colorCompoundBrandForeground1' as const,
    colorCompoundBrandForeground1Hover: '--colorCompoundBrandForeground1Hover' as const,
    colorCompoundBrandForeground1Pressed: '--colorCompoundBrandForeground1Pressed' as const,
    colorNeutralForegroundOnBrand: '--colorNeutralForegroundOnBrand' as const,
    colorNeutralForegroundInverted: '--colorNeutralForegroundInverted' as const,
    colorNeutralForegroundInvertedHover: '--colorNeutralForegroundInvertedHover' as const,
    colorNeutralForegroundInvertedPressed: '--colorNeutralForegroundInvertedPressed' as const,
    colorNeutralForegroundInvertedSelected: '--colorNeutralForegroundInvertedSelected' as const,
    colorNeutralForegroundInverted2: '--colorNeutralForegroundInverted2' as const,
    colorNeutralForegroundStaticInverted: '--colorNeutralForegroundStaticInverted' as const,
    colorNeutralForegroundInvertedLink: '--colorNeutralForegroundInvertedLink' as const,
    colorNeutralForegroundInvertedLinkHover: '--colorNeutralForegroundInvertedLinkHover' as const,
    colorNeutralForegroundInvertedLinkPressed: '--colorNeutralForegroundInvertedLinkPressed' as const,
    colorNeutralForegroundInvertedLinkSelected: '--colorNeutralForegroundInvertedLinkSelected' as const,
    colorNeutralForegroundInvertedDisabled: '--colorNeutralForegroundInvertedDisabled' as const,
    colorBrandForeground1: '--colorBrandForeground1' as const,
    colorBrandForeground2: '--colorBrandForeground2' as const,
    colorNeutralForeground1Static: '--colorNeutralForeground1Static' as const,
    colorBrandForegroundInverted: '--colorBrandForegroundInverted' as const,
    colorBrandForegroundInvertedHover: '--colorBrandForegroundInvertedHover' as const,
    colorBrandForegroundInvertedPressed: '--colorBrandForegroundInvertedPressed' as const,
    colorBrandForegroundOnLight: '--colorBrandForegroundOnLight' as const,
    colorBrandForegroundOnLightHover: '--colorBrandForegroundOnLightHover' as const,
    colorBrandForegroundOnLightPressed: '--colorBrandForegroundOnLightPressed' as const,
    colorBrandForegroundOnLightSelected: '--colorBrandForegroundOnLightSelected' as const,
    colorNeutralBackground1: '--colorNeutralBackground1' as const,
    colorNeutralBackground1Hover: '--colorNeutralBackground1Hover' as const,
    colorNeutralBackground1Pressed: '--colorNeutralBackground1Pressed' as const,
    colorNeutralBackground1Selected: '--colorNeutralBackground1Selected' as const,
    colorNeutralBackground2: '--colorNeutralBackground2' as const,
    colorNeutralBackground2Hover: '--colorNeutralBackground2Hover' as const,
    colorNeutralBackground2Pressed: '--colorNeutralBackground2Pressed' as const,
    colorNeutralBackground2Selected: '--colorNeutralBackground2Selected' as const,
    colorNeutralBackground3: '--colorNeutralBackground3' as const,
    colorNeutralBackground3Hover: '--colorNeutralBackground3Hover' as const,
    colorNeutralBackground3Pressed: '--colorNeutralBackground3Pressed' as const,
    colorNeutralBackground3Selected: '--colorNeutralBackground3Selected' as const,
    colorNeutralBackground4: '--colorNeutralBackground4' as const,
    colorNeutralBackground4Hover: '--colorNeutralBackground4Hover' as const,
    colorNeutralBackground4Pressed: '--colorNeutralBackground4Pressed' as const,
    colorNeutralBackground4Selected: '--colorNeutralBackground4Selected' as const,
    colorNeutralBackground5: '--colorNeutralBackground5' as const,
    colorNeutralBackground5Hover: '--colorNeutralBackground5Hover' as const,
    colorNeutralBackground5Pressed: '--colorNeutralBackground5Pressed' as const,
    colorNeutralBackground5Selected: '--colorNeutralBackground5Selected' as const,
    colorNeutralBackground6: '--colorNeutralBackground6' as const,
    colorNeutralBackgroundInverted: '--colorNeutralBackgroundInverted' as const,
    colorNeutralBackgroundStatic: '--colorNeutralBackgroundStatic' as const,
    colorSubtleBackground: '--colorSubtleBackground' as const,
    colorSubtleBackgroundHover: '--colorSubtleBackgroundHover' as const,
    colorSubtleBackgroundPressed: '--colorSubtleBackgroundPressed' as const,
    colorSubtleBackgroundSelected: '--colorSubtleBackgroundSelected' as const,
    colorSubtleBackgroundLightAlphaHover: '--colorSubtleBackgroundLightAlphaHover' as const,
    colorSubtleBackgroundLightAlphaPressed: '--colorSubtleBackgroundLightAlphaPressed' as const,
    colorSubtleBackgroundLightAlphaSelected: '--colorSubtleBackgroundLightAlphaSelected' as const,
    colorSubtleBackgroundInverted: '--colorSubtleBackgroundInverted' as const,
    colorSubtleBackgroundInvertedHover: '--colorSubtleBackgroundInvertedHover' as const,
    colorSubtleBackgroundInvertedPressed: '--colorSubtleBackgroundInvertedPressed' as const,
    colorSubtleBackgroundInvertedSelected: '--colorSubtleBackgroundInvertedSelected' as const,
    colorTransparentBackground: '--colorTransparentBackground' as const,
    colorTransparentBackgroundHover: '--colorTransparentBackgroundHover' as const,
    colorTransparentBackgroundPressed: '--colorTransparentBackgroundPressed' as const,
    colorTransparentBackgroundSelected: '--colorTransparentBackgroundSelected' as const,
    colorNeutralBackgroundDisabled: '--colorNeutralBackgroundDisabled' as const,
    colorNeutralBackgroundInvertedDisabled: '--colorNeutralBackgroundInvertedDisabled' as const,
    colorNeutralStencil1: '--colorNeutralStencil1' as const,
    colorNeutralStencil2: '--colorNeutralStencil2' as const,
    colorNeutralStencil1Alpha: '--colorNeutralStencil1Alpha' as const,
    colorNeutralStencil2Alpha: '--colorNeutralStencil2Alpha' as const,
    colorBackgroundOverlay: '--colorBackgroundOverlay' as const,
    colorScrollbarOverlay: '--colorScrollbarOverlay' as const,
    colorBrandBackground: '--colorBrandBackground' as const,
    colorBrandBackgroundHover: '--colorBrandBackgroundHover' as const,
    colorBrandBackgroundPressed: '--colorBrandBackgroundPressed' as const,
    colorBrandBackgroundSelected: '--colorBrandBackgroundSelected' as const,
    colorCompoundBrandBackground: '--colorCompoundBrandBackground' as const,
    colorCompoundBrandBackgroundHover: '--colorCompoundBrandBackgroundHover' as const,
    colorCompoundBrandBackgroundPressed: '--colorCompoundBrandBackgroundPressed' as const,
    colorBrandBackgroundStatic: '--colorBrandBackgroundStatic' as const,
    colorBrandBackground2: '--colorBrandBackground2' as const,
    colorBrandBackground2Pressed: '--colorBrandBackground2Pressed' as const,
    colorBrandBackground2Hover: '--colorBrandBackground2Hover' as const,
    colorBrandBackgroundInverted: '--colorBrandBackgroundInverted' as const,
    colorBrandBackgroundInvertedHover: '--colorBrandBackgroundInvertedHover' as const,
    colorBrandBackgroundInvertedPressed: '--colorBrandBackgroundInvertedPressed' as const,
    colorBrandBackgroundInvertedSelected: '--colorBrandBackgroundInvertedSelected' as const,
    colorNeutralStrokeAccessible: '--colorNeutralStrokeAccessible' as const,
    colorNeutralStrokeAccessibleHover: '--colorNeutralStrokeAccessibleHover' as const,
    colorNeutralStrokeAccessiblePressed: '--colorNeutralStrokeAccessiblePressed' as const,
    colorNeutralStrokeAccessibleSelected: '--colorNeutralStrokeAccessibleSelected' as const,
    colorNeutralStrokeAlpha: '--colorNeutralStrokeAlpha' as const,
    colorNeutralStroke1: '--colorNeutralStroke1' as const,
    colorNeutralStroke1Hover: '--colorNeutralStroke1Hover' as const,
    colorNeutralStroke1Pressed: '--colorNeutralStroke1Pressed' as const,
    colorNeutralStroke1Selected: '--colorNeutralStroke1Selected' as const,
    colorNeutralStroke2: '--colorNeutralStroke2' as const,
    colorNeutralStroke3: '--colorNeutralStroke3' as const,
    colorNeutralStrokeOnBrand: '--colorNeutralStrokeOnBrand' as const,
    colorNeutralStrokeOnBrand2: '--colorNeutralStrokeOnBrand2' as const,
    colorNeutralStrokeOnBrand2Hover: '--colorNeutralStrokeOnBrand2Hover' as const,
    colorNeutralStrokeOnBrand2Pressed: '--colorNeutralStrokeOnBrand2Pressed' as const,
    colorNeutralStrokeOnBrand2Selected: '--colorNeutralStrokeOnBrand2Selected' as const,
    colorBrandStroke1: '--colorBrandStroke1' as const,
    colorBrandStroke2: '--colorBrandStroke2' as const,
    colorCompoundBrandStroke: '--colorCompoundBrandStroke' as const,
    colorCompoundBrandStrokeHover: '--colorCompoundBrandStrokeHover' as const,
    colorCompoundBrandStrokePressed: '--colorCompoundBrandStrokePressed' as const,
    colorNeutralStrokeDisabled: '--colorNeutralStrokeDisabled' as const,
    colorNeutralStrokeInvertedDisabled: '--colorNeutralStrokeInvertedDisabled' as const,
    colorTransparentStroke: '--colorTransparentStroke' as const,
    colorTransparentStrokeInteractive: '--colorTransparentStrokeInteractive' as const,
    colorTransparentStrokeDisabled: '--colorTransparentStrokeDisabled' as const,
    colorStrokeFocus1: '--colorStrokeFocus1' as const,
    colorStrokeFocus2: '--colorStrokeFocus2' as const,
    colorNeutralShadowAmbient: '--colorNeutralShadowAmbient' as const,
    colorNeutralShadowKey: '--colorNeutralShadowKey' as const,
    colorNeutralShadowAmbientLighter: '--colorNeutralShadowAmbientLighter' as const,
    colorNeutralShadowKeyLighter: '--colorNeutralShadowKeyLighter' as const,
    colorNeutralShadowAmbientDarker: '--colorNeutralShadowAmbientDarker' as const,
    colorNeutralShadowKeyDarker: '--colorNeutralShadowKeyDarker' as const,
    colorBrandShadowAmbient: '--colorBrandShadowAmbient' as const,
    colorBrandShadowKey: '--colorBrandShadowKey' as const,
    colorPaletteDarkOrangeForeground1: '--colorPaletteDarkOrangeForeground1' as const,
    colorPaletteRedForeground1: '--colorPaletteRedForeground1' as const,
    colorPaletteYellowBackground2: '--colorPaletteYellowBackground2' as const,
    colorPaletteDarkOrangeBorderActive: '--colorPaletteDarkOrangeBorderActive' as const,
    colorPaletteGrapeBorderActive: '--colorPaletteGrapeBorderActive' as const
  };
  
  export const FluentV9FontFamilyTokens = {
    fontFamilyBase: '--fontFamilyBase' as const,
    fontFamilyMonospace: '--fontFamilyMonospace' as const,
    fontFamilyNumeric: '--fontFamilyNumeric' as const
  };
  
  export const FluentV9FontSizeTokens = {
    fontSizeBase100: '--fontSizeBase100' as const,
    fontSizeBase200: '--fontSizeBase200' as const,
    fontSizeBase300: '--fontSizeBase300' as const,
    fontSizeBase400: '--fontSizeBase400' as const,
    fontSizeBase500: '--fontSizeBase500' as const,
    fontSizeBase600: '--fontSizeBase600' as const,
    fontSizeHero700: '--fontSizeHero700' as const,
    fontSizeHero800: '--fontSizeHero800' as const,
    fontSizeHero900: '--fontSizeHero900' as const,
    fontSizeHero1000: '--fontSizeHero1000' as const
  };
  
  export const FluentV9FontWeightTokens = {
    fontWeightRegular: '--fontWeightRegular' as const,
    fontWeightMedium: '--fontWeightMedium' as const,
    fontWeightSemibold: '--fontWeightSemibold' as const,
    fontWeightBold: '--fontWeightBold' as const
  };
  
  export const FluentV9BorderRadiusTokens = {
    borderRadiusNone: '--borderRadiusNone' as const,
    borderRadiusSmall: '--borderRadiusSmall' as const,
    borderRadiusMedium: '--borderRadiusMedium' as const,
    borderRadiusLarge: '--borderRadiusLarge' as const,
    borderRadiusXLarge: '--borderRadiusXLarge' as const,
    borderRadiusCircular: '--borderRadiusCircular' as const
  };
  
  export const FluentV9LineHeightTokens = {
    lineHeightBase100: '--lineHeightBase100' as const,
    lineHeightBase200: '--lineHeightBase200' as const,
    lineHeightBase300: '--lineHeightBase300' as const,
    lineHeightBase400: '--lineHeightBase400' as const,
    lineHeightBase500: '--lineHeightBase500' as const,
    lineHeightBase600: '--lineHeightBase600' as const,
    lineHeightHero700: '--lineHeightHero700' as const,
    lineHeightHero800: '--lineHeightHero800' as const,
    lineHeightHero900: '--lineHeightHero900' as const,
    lineHeightHero1000: '--lineHeightHero1000' as const
  };
  
  export const FluentV9ShadowTokens = {
    shadow2: '--shadow2' as const,
    shadow4: '--shadow4' as const,
    shadow8: '--shadow8' as const,
    shadow16: '--shadow16' as const,
    shadow28: '--shadow28' as const,
    shadow64: '--shadow64' as const,
    shadow2Brand: '--shadow2Brand' as const,
    shadow4Brand: '--shadow4Brand' as const,
    shadow8Brand: '--shadow8Brand' as const,
    shadow16Brand: '--shadow16Brand' as const,
    shadow28Brand: '--shadow28Brand' as const,
    shadow64Brand: '--shadow64Brand' as const
  };
  
  export const FluentV9StrokeWidthTokens = {
    strokeWidthThin: '--strokeWidthThin' as const,
    strokeWidthThick: '--strokeWidthThick' as const,
    strokeWidthThicker: '--strokeWidthThicker' as const,
    strokeWidthThickest: '--strokeWidthThickest' as const
  };
  
  export const FluentV9SpacingTokens = {
    spacingHorizontalNone: '--spacingHorizontalNone' as const,
    spacingHorizontalXXS: '--spacingHorizontalXXS' as const,
    spacingHorizontalXS: '--spacingHorizontalXS' as const,
    spacingHorizontalSNudge: '--spacingHorizontalSNudge' as const,
    spacingHorizontalS: '--spacingHorizontalS' as const,
    spacingHorizontalMNudge: '--spacingHorizontalMNudge' as const,
    spacingHorizontalM: '--spacingHorizontalM' as const,
    spacingHorizontalL: '--spacingHorizontalL' as const,
    spacingHorizontalXL: '--spacingHorizontalXL' as const,
    spacingHorizontalXXL: '--spacingHorizontalXXL' as const,
    spacingHorizontalXXXL: '--spacingHorizontalXXXL' as const,
    spacingVerticalNone: '--spacingVerticalNone' as const,
    spacingVerticalXXS: '--spacingVerticalXXS' as const,
    spacingVerticalXS: '--spacingVerticalXS' as const,
    spacingVerticalSNudge: '--spacingVerticalSNudge' as const,
    spacingVerticalS: '--spacingVerticalS' as const,
    spacingVerticalMNudge: '--spacingVerticalMNudge' as const,
    spacingVerticalM: '--spacingVerticalM' as const,
    spacingVerticalL: '--spacingVerticalL' as const,
    spacingVerticalXL: '--spacingVerticalXL' as const,
    spacingVerticalXXL: '--spacingVerticalXXL' as const,
    spacingVerticalXXXL: '--spacingVerticalXXXL' as const
  };
  
  export const FluentV9DurationTokens = {
    durationUltraFast: '--durationUltraFast' as const,
    durationFaster: '--durationFaster' as const,
    durationFast: '--durationFast' as const,
    durationNormal: '--durationNormal' as const,
    durationGentle: '--durationGentle' as const,
    durationSlow: '--durationSlow' as const,
    durationSlower: '--durationSlower' as const,
    durationUltraSlow: '--durationUltraSlow' as const
  };
  
  export const FluentV9CurveTokens = {
    curveAccelerateMax: '--curveAccelerateMax' as const,
    curveAccelerateMid: '--curveAccelerateMid' as const,
    curveAccelerateMin: '--curveAccelerateMin' as const,
    curveDecelerateMax: '--curveDecelerateMax' as const,
    curveDecelerateMid: '--curveDecelerateMid' as const,
    curveDecelerateMin: '--curveDecelerateMin' as const,
    curveEasyEaseMax: '--curveEasyEaseMax' as const,
    curveEasyEase: '--curveEasyEase' as const,
    curveLinear: '--curveLinear' as const
  };